//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerDL.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagerSQLConn : DbContext
    {
        public ProjectManagerSQLConn()
            : base("name=ProjectManagerSQLConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_PRNT_TASK> T_PRNT_TASK { get; set; }
        public virtual DbSet<T_PROJ> T_PROJ { get; set; }
        public virtual DbSet<T_TASK> T_TASK { get; set; }
        public virtual DbSet<T_USR> T_USR { get; set; }
    }
}
