//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerDL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TASK
    {
        public int TASK_ID { get; set; }
        public string TASK_NM { get; set; }
        public Nullable<int> PRNT_TASK_ID { get; set; }
        public int PRIORITY { get; set; }
        public System.DateTime STRT_DT { get; set; }
        public System.DateTime END_DT { get; set; }
        public int PROJ_ID { get; set; }
        public int USR_ID { get; set; }
        public string STATUS { get; set; }
    
        public virtual T_PRNT_TASK T_PRNT_TASK { get; set; }
        public virtual T_PROJ T_PROJ { get; set; }
        public virtual T_USR T_USR { get; set; }
    }
}
